//
//  KeyboardViewController.swift
//
//  Created by Ethan Sarif-Kattan on 09/07/2019.
//  Copyright © 2019 Ethan Sarif-Kattan. All rights reserved.
//

import UIKit

var proxy : UITextDocumentProxy!

class KeyboardViewController: UIInputViewController,UICollectionViewDelegate,UICollectionViewDataSource {
    
    
    @IBOutlet var nextKeyboardButton: UIButton!
    @IBOutlet weak var topView: UIView!
    
    var keyboardView: UIView!
    var keys: [UIButton] = []
    var paddingViews: [UIButton] = []
    var backspaceTimer: Timer?
    
    enum KeyboardState{
        case letters
        case numbers
        case symbols
    }
    
    enum ShiftButtonState {
        case normal
        case shift
        case caps
    }
    
    var keyboardState: KeyboardState = .letters
    var shiftButtonState:ShiftButtonState = .normal
    
    @IBOutlet weak var stackView1: UIStackView!
    @IBOutlet weak var stackView2: UIStackView!
    @IBOutlet weak var stackView3: UIStackView!
    @IBOutlet weak var stackView4: UIStackView!
    
    var selectedFontIndex = 0
    
    
    override func updateViewConstraints() {
        super.updateViewConstraints()
        // Add custom view sizing constraints here
        keyboardView.frame.size = view.frame.size
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        proxy = textDocumentProxy as UITextDocumentProxy
        loadInterface()
        self.nextKeyboardButton.addTarget(self, action: #selector(handleInputModeList(from:with:)), for: .allTouchEvents)
        
    }
    var collectionView: UICollectionView!
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        let layout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
        layout.sectionInset = UIEdgeInsets(top: 10, left: 5, bottom: 10, right: 5)
        layout.itemSize = CGSize(width: 100, height: 40)
        layout.scrollDirection = .horizontal
        layout.minimumInteritemSpacing = 0
        layout.minimumLineSpacing = 0
        
        collectionView = UICollectionView(frame: self.view.frame, collectionViewLayout: layout)
        collectionView.dataSource = self
        collectionView.delegate = self
        collectionView.register(UICollectionViewCell.self, forCellWithReuseIdentifier: "Cell")
        collectionView.backgroundColor = .clear
        collectionView.showsHorizontalScrollIndicator = false
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        self.topView.addSubview(collectionView)
        
        collectionView.topAnchor.constraint(equalTo: topView.topAnchor,constant: 0.0).isActive = true
        collectionView.bottomAnchor.constraint(equalTo: topView.bottomAnchor, constant: 0.0).isActive = true
        collectionView.leadingAnchor.constraint(equalTo: topView.leadingAnchor).isActive = true
        collectionView.trailingAnchor.constraint(equalTo: topView.trailingAnchor).isActive = true
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return self.FontDic.count
    }
    
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "Cell", for: indexPath)
        let button = UIButton(frame: CGRect(x: 0, y: 0, width: cell.bounds.size.width, height: 40))
        let name = FontDic[indexPath.row]
        button.setTitle(name["font_name"] as? String, for: .normal)
        button.titleLabel?.font = UIFont.boldSystemFont(ofSize: 16)
        button.setTitleColor(.darkGray, for: .normal)
        button.tag = indexPath.row
        cell.contentView.addSubview(button)
        
        button.addTarget(self, action: #selector(fontButtonPressed(sender:)), for: .touchUpInside)
        button.backgroundColor = .white
        
        return cell
        
    }
    
    @objc func fontButtonPressed(sender: UIButton){
        self.selectedFontIndex = sender.tag
        self.loadKeys()
    }
    
    override func viewWillLayoutSubviews() {
        self.nextKeyboardButton.isHidden = !self.needsInputModeSwitchKey
        super.viewWillLayoutSubviews()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        let heightConstraint = NSLayoutConstraint(item: view!, attribute: NSLayoutConstraint.Attribute.height, relatedBy: NSLayoutConstraint.Relation.equal, toItem: nil, attribute: NSLayoutConstraint.Attribute.notAnAttribute, multiplier: 1.0, constant: 250)
        view.addConstraint(heightConstraint)
        
    }
    
    
    func loadInterface(){
        let keyboardNib = UINib(nibName: "Keyboard", bundle: nil)
        keyboardView = keyboardNib.instantiate(withOwner: self, options: nil)[0] as? UIView
        view.addSubview(keyboardView)
        loadKeys()
    }
    
    func addPadding(to stackView: UIStackView, width: CGFloat, key: String){
        let padding = UIButton(frame: CGRect(x: 0, y: 0, width: 5, height: 5))
        padding.setTitleColor(.clear, for: .normal)
        padding.alpha = 0.02
        padding.widthAnchor.constraint(equalToConstant: width).isActive = true
        
        //if we want to use this padding as a key, for example the a and l buttons
        let keyToDisplay = shiftButtonState == .normal ? key : key.capitalized
        padding.layer.setValue(key, forKey: "original")
        padding.layer.setValue(keyToDisplay, forKey: "keyToDisplay")
        padding.layer.setValue(false, forKey: "isSpecial")
        padding.addTarget(self, action: #selector(keyPressedTouchUp), for: .touchUpInside)
        padding.addTarget(self, action: #selector(keyTouchDown), for: .touchDown)
        padding.addTarget(self, action: #selector(keyUntouched), for: .touchDragExit)
        
        paddingViews.append(padding)
        stackView.addArrangedSubview(padding)
    }
    
    func loadKeys(){
        keys.forEach{$0.removeFromSuperview()}
        paddingViews.forEach{$0.removeFromSuperview()}
        
        let buttonWidth = (UIScreen.main.bounds.width - 6) / CGFloat(Constants.letterKeys[0].count)
        
        var keyboard: [[String]]
        
        //start padding
        switch keyboardState {
        case .letters:
            keyboard = Constants.letterKeys
            addPadding(to: stackView2, width: buttonWidth/2, key: "a")
        case .numbers:
            keyboard = Constants.numberKeys
        case .symbols:
            keyboard = Constants.symbolKeys
        }
        let numRows = keyboard.count
        for row in 0...numRows - 1{
            for col in 0...keyboard[row].count - 1{
                let button = UIButton(type: .custom)
                button.backgroundColor = Constants.keyNormalColour
                button.setTitleColor(.black, for: .normal)
                let key = keyboard[row][col]
                let capsKey = keyboard[row][col].capitalized
                let keyToDisplay = shiftButtonState == .normal ? key : capsKey
                button.layer.setValue(key, forKey: "original")
                button.layer.setValue(keyToDisplay, forKey: "keyToDisplay")
                button.layer.setValue(false, forKey: "isSpecial")
                let name = FontDic[selectedFontIndex]
                let font = name["font"] as! Dictionary<String, String>
                button.setTitle(font[keyToDisplay], for: .normal)
               // button.setTitle(keyToDisplay, for: .normal)
                button.layer.borderColor = keyboardView.backgroundColor?.cgColor
                button.layer.borderWidth = 4
                button.addTarget(self, action: #selector(keyPressedTouchUp), for: .touchUpInside)
                button.addTarget(self, action: #selector(keyTouchDown), for: .touchDown)
                button.addTarget(self, action: #selector(keyUntouched), for: .touchDragExit)
                button.addTarget(self, action: #selector(keyMultiPress(_:event:)), for: .touchDownRepeat)
                
                if key == "⌫"{
                    let longPressRecognizer = UILongPressGestureRecognizer(target: self, action: #selector(keyLongPressed(_:)))
                    button.addGestureRecognizer(longPressRecognizer)
                }
                
                button.layer.cornerRadius = buttonWidth/4
                keys.append(button)
                switch row{
                case 0: stackView1.addArrangedSubview(button)
                case 1: stackView2.addArrangedSubview(button)
                case 2: stackView3.addArrangedSubview(button)
                case 3: stackView4.addArrangedSubview(button)
                default:
                    break
                }
                if key == "🌐"{
                    nextKeyboardButton = button
                }
                
                //top row is longest row so it should decide button width
                print("button width: ", buttonWidth)
                if key == "⌫" || key == "↩" || key == "#+=" || key == "ABC" || key == "123" || key == "⬆️" || key == "🌐"{
                    button.widthAnchor.constraint(equalToConstant: buttonWidth + buttonWidth/2).isActive = true
                    button.layer.setValue(true, forKey: "isSpecial")
                    button.backgroundColor = Constants.specialKeyNormalColour
                    if key == "⬆️" {
                        if shiftButtonState != .normal{
                            button.backgroundColor = Constants.keyPressedColour
                        }
                        if shiftButtonState == .caps{
                            button.setTitle("⏫", for: .normal)
                        }
                    }
                }else if (keyboardState == .numbers || keyboardState == .symbols) && row == 2{
                    button.widthAnchor.constraint(equalToConstant: buttonWidth * 1.4).isActive = true
                }else if key != "space"{
                    button.widthAnchor.constraint(equalToConstant: buttonWidth).isActive = true
                }else{
                    button.layer.setValue(key, forKey: "original")
                    button.setTitle(key, for: .normal)
                }
            }
        }
        
        
        //end padding
        switch keyboardState {
        case .letters:
            addPadding(to: stackView2, width: buttonWidth/2, key: "l")
        case .numbers:
            break
        case .symbols: break
        }
        
    }
    
    func changeKeyboardToNumberKeys(){
        keyboardState = .numbers
        shiftButtonState = .normal
        loadKeys()
    }
    func changeKeyboardToLetterKeys(){
        keyboardState = .letters
        loadKeys()
    }
    func changeKeyboardToSymbolKeys(){
        keyboardState = .symbols
        loadKeys()
    }
    func handlDeleteButtonPressed(){
        proxy.deleteBackward()
    }
    
    @IBAction func keyPressedTouchUp(_ sender: UIButton) {
        guard let originalKey = sender.layer.value(forKey: "original") as? String, let keyToDisplay = sender.layer.value(forKey: "keyToDisplay") as? String else {return}
        
        //guard let originalKey = sender.layer.value(forKey: "original") as? String, let keyToDisplay = sender.titleLabel?.text else {return}
        
        guard let isSpecial = sender.layer.value(forKey: "isSpecial") as? Bool else {return}
        sender.backgroundColor = isSpecial ? Constants.specialKeyNormalColour : Constants.keyNormalColour
        
        switch originalKey {
        case "⌫":
            if shiftButtonState == .shift {
                shiftButtonState = .normal
                loadKeys()
            }
            handlDeleteButtonPressed()
        case "space":
            proxy.insertText(" ")
        case "🌐":
            break
        case "↩":
            proxy.insertText("\n")
        case "123":
            changeKeyboardToNumberKeys()
        case "ABC":
            changeKeyboardToLetterKeys()
        case "#+=":
            changeKeyboardToSymbolKeys()
        case "⬆️":
            shiftButtonState = shiftButtonState == .normal ? .shift : .normal
            loadKeys()
        default:
            if shiftButtonState == .shift {
                shiftButtonState = .normal
                loadKeys()
            }
            
            let name = FontDic[selectedFontIndex]
            let font = name["font"] as! Dictionary<String, String>
            proxy.insertText(font[keyToDisplay] ?? "test")
            
        }
    }
    
    @objc func keyMultiPress(_ sender: UIButton, event: UIEvent){
        guard let originalKey = sender.layer.value(forKey: "original") as? String else {return}
        
        let touch: UITouch = event.allTouches!.first!
        if (touch.tapCount == 2 && originalKey == "⬆️") {
            shiftButtonState = .caps
            loadKeys()
        }
    }
    
    @objc func keyLongPressed(_ gesture: UIGestureRecognizer){
        if gesture.state == .began {
            backspaceTimer = Timer.scheduledTimer(withTimeInterval: 0.1, repeats: true) { (timer) in
                self.handlDeleteButtonPressed()
            }
        } else if gesture.state == .ended || gesture.state == .cancelled {
            backspaceTimer?.invalidate()
            backspaceTimer = nil
            (gesture.view as! UIButton).backgroundColor = Constants.specialKeyNormalColour
        }
    }
    
    @objc func keyUntouched(_ sender: UIButton){
        guard let isSpecial = sender.layer.value(forKey: "isSpecial") as? Bool else {return}
        sender.backgroundColor = isSpecial ? Constants.specialKeyNormalColour : Constants.keyNormalColour
    }
    
    @objc func keyTouchDown(_ sender: UIButton){
        sender.backgroundColor = Constants.keyPressedColour
    }
    
    override func textWillChange(_ textInput: UITextInput?) {
        // The app is about to change the document's contents. Perform any preparation here.
        
    }
    
    override func textDidChange(_ textInput: UITextInput?) {
        // The app has just changed the document's contents, the document context has been updated.
        
        var textColor: UIColor
        let proxy = self.textDocumentProxy
        if proxy.keyboardAppearance == UIKeyboardAppearance.dark {
            
            textColor = UIColor.white
            
        } else {
            
            textColor = UIColor.black
            
        }
        self.nextKeyboardButton.setTitleColor(textColor, for: [])
    }
        
    let FontDic = [
        
        [
            "font_name":"Ｆｏｎｔ １",
            "font":[
                "A":"Ａ",
                "B":"Ｂ",
                "C":"Ｃ",
                "D":"Ｄ",
                "E":"Ｅ",
                "F":"Ｆ",
                "G":"Ｇ",
                "H":"Ｈ",
                "I":"Ｉ",
                "J":"Ｊ",
                "K":"Ｋ",
                "L":"Ｌ",
                "M":"Ｍ",
                "N":"Ｎ",
                "O":"Ｏ",
                "P":"Ｐ",
                "Q":"Ｑ",
                "R":"Ｒ",
                "S":"Ｓ",
                "T":"Ｔ",
                "U":"Ｕ",
                "V":"Ｖ",
                "W":"Ｗ",
                "X":"Ｘ",
                "Y":"Ｙ",
                "Z":"Ｚ",
                "a":"ａ",
                "b":"ｂ",
                "c":"ｃ",
                "d":"ｄ",
                "e":"ｅ",
                "f":"ｆ",
                "g":"ｇ",
                "h":"ｈ",
                "i":"ｉ",
                "j":"ｊ",
                "k":"ｋ",
                "l":"ｌ",
                "m":"ｍ",
                "n":"ｎ",
                "o":"ｏ",
                "p":"ｐ",
                "q":"ｑ",
                "r":"ｒ",
                "s":"ｓ",
                "t":"ｔ",
                "u":"ｕ",
                "v":"ｖ",
                "w":"ｗ",
                "x":"ｘ",
                "y":"ｙ",
                "z":"ｚ",
                "0":"０",
                "1":"１",
                "2":"２",
                "3":"３",
                "4":"４",
                "5":"５",
                "6":"６",
                "7":"７",
                "8":"８",
                "9":"９",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
                

            ]
        ],
        [
            "font_name":"𝑭𝒐𝒏𝒕 𝟐",
            "font":[
                "A":"𝑨",
                "B":"𝑩",
                "C":"𝑪",
                "D":"𝑫",
                "E":"𝑬",
                "F":"𝑭",
                "G":"𝑮",
                "H":"𝑯",
                "I":"𝑰",
                "J":"𝑱",
                "K":"𝑲",
                "L":"𝑳",
                "M":"𝑴",
                "N":"𝑵",
                "O":"𝑶",
                "P":"𝑷",
                "Q":"𝑸",
                "R":"𝑹",
                "S":"𝑺",
                "T":"𝑻",
                "U":"𝑼",
                "V":"𝑽",
                "W":"𝑾",
                "X":"𝑿",
                "Y":"𝒀",
                "Z":"𝒁",
                "a":"𝒂",
                "b":"𝒃",
                "c":"𝒄",
                "d":"𝒅",
                "e":"𝒆",
                "f":"𝒇",
                "g":"𝒈",
                "h":"𝒉",
                "i":"𝒊",
                "j":"𝒋",
                "k":"𝒌",
                "l":"𝒍",
                "m":"𝒎",
                "n":"𝒏",
                "o":"𝒐",
                "p":"𝒑",
                "q":"𝒒",
                "r":"𝒓",
                "s":"𝒔",
                "t":"𝒕",
                "u":"𝒖",
                "v":"𝒗",
                "w":"𝒘",
                "x":"𝒙",
                "y":"𝒚",
                "z":"𝒛",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"

            ]
        ],
        
        [
            "font_name":"𝓕𝓸𝓷𝓽 𝟑",
            "font":[
                "A":"𝓐",
                "B":"𝓑",
                "C":"𝓒",
                "D":"𝓓",
                "E":"𝓔",
                "F":"𝓕",
                "G":"𝓖",
                "H":"𝓗",
                "I":"𝓘",
                "J":"𝓙",
                "K":"𝓚",
                "L":"𝓛",
                "M":"𝓜",
                "N":"𝓝",
                "O":"𝓞",
                "P":"𝓟",
                "Q":"𝓠",
                "R":"𝓡",
                "S":"𝓢",
                "T":"𝓣",
                "U":"𝓤",
                "V":"𝓥",
                "W":"𝓦",
                "X":"𝓧",
                "Y":"𝓨",
                "Z":"𝓩",
                "a":"𝓪",
                "b":"𝓫",
                "c":"𝓬",
                "d":"𝓭",
                "e":"𝓮",
                "f":"𝓯",
                "g":"𝓰",
                "h":"𝓱",
                "i":"𝓲",
                "j":"𝓳",
                "k":"𝓴",
                "l":"𝓵",
                "m":"𝓶",
                "n":"𝓷",
                "o":"𝓸",
                "p":"𝓹",
                "q":"𝓺",
                "r":"𝓻",
                "s":"𝓼",
                "t":"𝓽",
                "u":"𝓾",
                "v":"𝓿",
                "w":"𝔀",
                "x":"𝔁",
                "y":"𝔂",
                "z":"𝔃",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ],
        
        [
            "font_name":"𝐅𝐨𝐧𝐭 𝟒",
            "font":[
                "A":"𝐀",
                "B":"𝐁",
                "C":"𝐂",
                "D":"𝐃",
                "E":"𝐄",
                "F":"𝐅",
                "G":"𝐆",
                "H":"𝐇",
                "I":"𝐈",
                "J":"𝐉",
                "K":"𝐊",
                "L":"𝐋",
                "M":"𝐌",
                "N":"𝐍",
                "O":"𝐎",
                "P":"𝐏",
                "Q":"𝐐",
                "R":"𝐑",
                "S":"𝐒",
                "T":"𝐓",
                "U":"𝐔",
                "V":"𝐕",
                "W":"𝐖",
                "X":"𝐗",
                "Y":"𝐘",
                "Z":"𝐙",
                "a":"𝐚",
                "b":"𝐛",
                "c":"𝐜",
                "d":"𝐝",
                "e":"𝐞",
                "f":"𝐟",
                "g":"𝐠",
                "h":"𝐡",
                "i":"𝐢",
                "j":"𝐣",
                "k":"𝐤",
                "l":"𝐥",
                "m":"𝐦",
                "n":"𝐧",
                "o":"𝐨",
                "p":"𝐩",
                "q":"𝐪",
                "r":"𝐫",
                "s":"𝐬",
                "t":"𝐭",
                "u":"𝐮",
                "v":"𝐯",
                "w":"𝐰",
                "x":"𝐱",
                "y":"𝐲",
                "z":"𝐳",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ],
        
        [
            "font_name":"𝙵𝚘𝚗𝚝 𝟻",
            "font":[
                "A":"𝙰",
                "B":"𝙱",
                "C":"𝙲",
                "D":"𝙳",
                "E":"𝙴",
                "F":"𝙵",
                "G":"𝙶",
                "H":"𝙷",
                "I":"𝙸",
                "J":"𝙹",
                "K":"𝙺",
                "L":"𝙻",
                "M":"𝙼",
                "N":"𝙽",
                "O":"𝙾",
                "P":"𝙿",
                "Q":"𝚀",
                "R":"𝚁",
                "S":"𝚂",
                "T":"𝚃",
                "U":"𝚄",
                "V":"𝚅",
                "W":"𝚆",
                "X":"𝚇",
                "Y":"𝚈",
                "Z":"𝚉",
                "a":"𝚊",
                "b":"𝚋",
                "c":"𝚌",
                "d":"𝚍",
                "e":"𝚎",
                "f":"𝚏",
                "g":"𝚐",
                "h":"𝚑",
                "i":"𝚒",
                "j":"𝚓",
                "k":"𝚔",
                "l":"𝚕",
                "m":"𝚖",
                "n":"𝚗",
                "o":"𝚘",
                "p":"𝚙",
                "q":"𝚚",
                "r":"𝚛",
                "s":"𝚜",
                "t":"𝚝",
                "u":"𝚞",
                "v":"𝚟",
                "w":"𝚠",
                "x":"𝚡",
                "y":"𝚢",
                "z":"𝚣",
                "0":"𝟶",
                "1":"𝟷",
                "2":"𝟸",
                "3":"𝟹",
                "4":"𝟺",
                "5":"𝟻",
                "6":"𝟼",
                "7":"𝟽",
                "8":"𝟾",
                "9":"𝟿",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ],
        [
            "font_name":"𝔽𝕠𝕟𝕥 𝟞",
            "font":[
                "A":"𝔸",
                "B":"𝔹",
                "C":"ℂ",
                "D":"𝔻",
                "E":"𝔼",
                "F":"𝔽",
                "G":"𝔾",
                "H":"ℍ",
                "I":"𝕀",
                "J":"𝕁",
                "K":"𝕂",
                "L":"𝕃",
                "M":"𝕄",
                "N":"ℕ",
                "O":"𝕆",
                "P":"ℙ",
                "Q":"ℚ",
                "R":"ℝ",
                "S":"𝕊",
                "T":"𝕋",
                "U":"𝕌",
                "V":"𝕍",
                "W":"𝕎",
                "X":"𝕏",
                "Y":"𝕐",
                "Z":"ℤ",
                "a":"𝕒",
                "b":"𝕓",
                "c":"𝕔",
                "d":"𝕕",
                "e":"𝕖",
                "f":"𝕗",
                "g":"𝕘",
                "h":"𝕙",
                "i":"𝕚",
                "j":"𝕛",
                "k":"𝕜",
                "l":"𝕝",
                "m":"𝕞",
                "n":"𝕟",
                "o":"𝕠",
                "p":"𝕡",
                "q":"𝕢",
                "r":"𝕣",
                "s":"𝕤",
                "t":"𝕥",
                "u":"𝕦",
                "v":"𝕧",
                "w":"𝕨",
                "x":"𝕩",
                "y":"𝕪",
                "z":"𝕫",
                "0":"𝟘",
                "1":"𝟙",
                "2":"𝟚",
                "3":"𝟛",
                "4":"𝟜",
                "5":"𝟝",
                "6":"𝟞",
                "7":"𝟟",
                "8":"𝟠",
                "9":"𝟡",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ],
        [
            "font_name":"Ⓕⓞⓝⓣ ⑦",
            "font":[
                "A":"Ⓐ",
                "B":"Ⓑ",
                "C":"Ⓒ",
                "D":"Ⓓ",
                "E":"Ⓔ",
                "F":"Ⓕ",
                "G":"Ⓖ",
                "H":"Ⓗ",
                "I":"Ⓘ",
                "J":"Ⓙ",
                "K":"Ⓚ",
                "L":"Ⓛ",
                "M":"Ⓜ",
                "N":"Ⓝ",
                "O":"Ⓞ",
                "P":"Ⓟ",
                "Q":"Ⓠ",
                "R":"Ⓡ",
                "S":"Ⓢ",
                "T":"Ⓣ",
                "U":"Ⓤ",
                "V":"Ⓥ",
                "W":"Ⓦ",
                "X":"Ⓧ",
                "Y":"Ⓨ",
                "Z":"Ⓩ",
                "a":"ⓐ",
                "b":"ⓑ",
                "c":"ⓒ",
                "d":"ⓓ",
                "e":"ⓔ",
                "f":"ⓕ",
                "g":"ⓖ",
                "h":"ⓗ",
                "i":"ⓘ",
                "j":"ⓙ",
                "k":"ⓚ",
                "l":"ⓛ",
                "m":"ⓜ",
                "n":"ⓝ",
                "o":"ⓞ",
                "p":"ⓟ",
                "q":"ⓠ",
                "r":"ⓡ",
                "s":"ⓢ",
                "t":"ⓣ",
                "u":"ⓤ",
                "v":"ⓥ",
                "w":"ⓦ",
                "x":"ⓧ",
                "y":"ⓨ",
                "z":"ⓩ",
                "0":"⓪",
                "1":"①",
                "2":"②",
                "3":"③",
                "4":"④",
                "5":"⑤",
                "6":"⑥",
                "7":"⑦",
                "8":"⑧",
                "9":"⑨",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ],
        [
            "font_name":"𝔽𝕠𝕟𝕥 8",
            "font":[
                "A":"𝔸",
                "B":"𝔹",
                "C":"ℂ",
                "D":"𝔻",
                "E":"𝔼",
                "F":"𝔽",
                "G":"𝔾",
                "H":"ℍ",
                "I":"𝕀",
                "J":"𝕁",
                "K":"𝕂",
                "L":"𝕃",
                "M":"𝕄",
                "N":"ℕ",
                "O":"𝕆",
                "P":"ℙ",
                "Q":"ℚ",
                "R":"ℝ",
                "S":"𝕊",
                "T":"𝕋",
                "U":"𝕌",
                "V":"𝕍",
                "W":"𝕎",
                "X":"𝕏",
                "Y":"𝕐",
                "Z":"ℤ",
                "a":"𝕒",
                "b":"𝕓",
                "c":"𝕔",
                "d":"𝕕",
                "e":"𝕖",
                "f":"𝕗",
                "g":"𝕘",
                "h":"𝕙",
                "i":"𝕚",
                "j":"𝕛",
                "k":"𝕜",
                "l":"𝕝",
                "m":"𝕞",
                "n":"𝕟",
                "o":"𝕠",
                "p":"𝕡",
                "q":"𝕢",
                "r":"𝕣",
                "s":"𝕤",
                "t":"𝕥",
                "u":"𝕦",
                "v":"𝕧",
                "w":"𝕨",
                "x":"𝕩",
                "y":"𝕪",
                "z":"𝕫",
                "0":"𝟘",
                "1":"𝟙",
                "2":"𝟚",
                "3":"𝟛",
                "4":"𝟜",
                "5":"𝟝",
                "6":"𝟞",
                "7":"𝟟",
                "8":"𝟠",
                "9":"𝟡",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        [
            "font_name":"Ｆｏｎｔ １0",
            "font":[
                "A":"Ａ",
                "B":"Ｂ",
                "C":"Ｃ",
                "D":"Ｄ",
                "E":"Ｅ",
                "F":"Ｆ",
                "G":"Ｇ",
                "H":"Ｈ",
                "I":"Ｉ",
                "J":"Ｊ",
                "K":"Ｋ",
                "L":"Ｌ",
                "M":"Ｍ",
                "N":"Ｎ",
                "O":"Ｏ",
                "P":"Ｐ",
                "Q":"Ｑ",
                "R":"Ｒ",
                "S":"Ｓ",
                "T":"Ｔ",
                "U":"Ｕ",
                "V":"Ｖ",
                "W":"Ｗ",
                "X":"Ｘ",
                "Y":"Ｙ",
                "Z":"Ｚ",
                "a":"ａ",
                "b":"ｂ",
                "c":"ｃ",
                "d":"ｄ",
                "e":"ｅ",
                "f":"ｆ",
                "g":"ｇ",
                "h":"ｈ",
                "i":"ｉ",
                "j":"ｊ",
                "k":"ｋ",
                "l":"ｌ",
                "m":"ｍ",
                "n":"ｎ",
                "o":"ｏ",
                "p":"ｐ",
                "q":"ｑ",
                "r":"ｒ",
                "s":"ｓ",
                "t":"ｔ",
                "u":"ｕ",
                "v":"ｖ",
                "w":"ｗ",
                "x":"ｘ",
                "y":"ｙ",
                "z":"ｚ",
                "0":"０",
                "1":"１",
                "2":"２",
                "3":"３",
                "4":"４",
                "5":"５",
                "6":"６",
                "7":"７",
                "8":"８",
                "9":"９",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
                

            ]
        ]
        
        ,
        
        [
            "font_name":"𝓣𝓮𝔁𝓽",
            "font":[
                "A":"𝙰",
                "B":"𝙱",
                "C":"𝙲",
                "D":"𝙳",
                "E":"𝙴",
                "F":"𝙵",
                "G":"𝙶",
                "H":"𝙷",
                "I":"𝙸",
                "J":"𝙹",
                "K":"𝙺",
                "L":"𝙻",
                "M":"𝙼",
                "N":"𝙽",
                "O":"𝙾",
                "P":"𝙿",
                "Q":"𝚀",
                "R":"𝚁",
                "S":"𝚂",
                "T":"𝚃",
                "U":"𝚄",
                "V":"𝚅",
                "W":"𝚆",
                "X":"𝚇",
                "Y":"𝚈",
                "Z":"𝚉",
                "a":"𝚊",
                "b":"𝚋",
                "c":"𝚌",
                "d":"𝚍",
                "e":"𝚎",
                "f":"𝚏",
                "g":"𝚐",
                "h":"𝚑",
                "i":"𝚒",
                "j":"𝚓",
                "k":"𝚔",
                "l":"𝚕",
                "m":"𝚖",
                "n":"𝚗",
                "o":"𝚘",
                "p":"𝚙",
                "q":"𝚚",
                "r":"𝚛",
                "s":"𝚜",
                "t":"𝚝",
                "u":"𝚞",
                "v":"𝚟",
                "w":"𝚠",
                "x":"𝚡",
                "y":"𝚢",
                "z":"𝚣",
                "0":"𝟶",
                "1":"𝟷",
                "2":"𝟸",
                "3":"𝟹",
                "4":"𝟺",
                "5":"𝟻",
                "6":"𝟼",
                "7":"𝟽",
                "8":"𝟾",
                "9":"𝟿",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,[
            "font_name":"ƬΣXƬ FΛПᑕY",
            "font":[
                "A":"𝙰",
                "B":"𝙱",
                "C":"𝙲",
                "D":"𝙳",
                "E":"𝙴",
                "F":"𝙵",
                "G":"𝙶",
                "H":"𝙷",
                "I":"𝙸",
                "J":"𝙹",
                "K":"𝙺",
                "L":"𝙻",
                "M":"𝙼",
                "N":"𝙽",
                "O":"𝙾",
                "P":"𝙿",
                "Q":"𝚀",
                "R":"𝚁",
                "S":"𝚂",
                "T":"𝚃",
                "U":"𝚄",
                "V":"𝚅",
                "W":"𝚆",
                "X":"𝚇",
                "Y":"𝚈",
                "Z":"𝚉",
                "a":"𝚊",
                "b":"𝚋",
                "c":"𝚌",
                "d":"𝚍",
                "e":"𝚎",
                "f":"𝚏",
                "g":"𝚐",
                "h":"𝚑",
                "i":"𝚒",
                "j":"𝚓",
                "k":"𝚔",
                "l":"𝚕",
                "m":"𝚖",
                "n":"𝚗",
                "o":"𝚘",
                "p":"𝚙",
                "q":"𝚚",
                "r":"𝚛",
                "s":"𝚜",
                "t":"𝚝",
                "u":"𝚞",
                "v":"𝚟",
                "w":"𝚠",
                "x":"𝚡",
                "y":"𝚢",
                "z":"𝚣",
                "0":"𝟶",
                "1":"𝟷",
                "2":"𝟸",
                "3":"𝟹",
                "4":"𝟺",
                "5":"𝟻",
                "6":"𝟼",
                "7":"𝟽",
                "8":"𝟾",
                "9":"𝟿",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        [
            "font_name":"𝔗𝔢𝔵𝔱 𝔉𝔞𝔫𝔠𝔶",
            "font":[
                "A":"𝐀",
                "B":"𝐁",
                "C":"𝐂",
                "D":"𝐃",
                "E":"𝐄",
                "F":"𝐅",
                "G":"𝐆",
                "H":"𝐇",
                "I":"𝐈",
                "J":"𝐉",
                "K":"𝐊",
                "L":"𝐋",
                "M":"𝐌",
                "N":"𝐍",
                "O":"𝐎",
                "P":"𝐏",
                "Q":"𝐐",
                "R":"𝐑",
                "S":"𝐒",
                "T":"𝐓",
                "U":"𝐔",
                "V":"𝐕",
                "W":"𝐖",
                "X":"𝐗",
                "Y":"𝐘",
                "Z":"𝐙",
                "a":"𝐚",
                "b":"𝐛",
                "c":"𝐜",
                "d":"𝐝",
                "e":"𝐞",
                "f":"𝐟",
                "g":"𝐠",
                "h":"𝐡",
                "i":"𝐢",
                "j":"𝐣",
                "k":"𝐤",
                "l":"𝐥",
                "m":"𝐦",
                "n":"𝐧",
                "o":"𝐨",
                "p":"𝐩",
                "q":"𝐪",
                "r":"𝐫",
                "s":"𝐬",
                "t":"𝐭",
                "u":"𝐮",
                "v":"𝐯",
                "w":"𝐰",
                "x":"𝐱",
                "y":"𝐲",
                "z":"𝐳",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        
        [
            "font_name":"𝙏𝙚𝙭𝙩 𝙁𝙖𝙣𝙘𝙮",
            "font":[
                "A":"𝐀",
                "B":"𝐁",
                "C":"𝐂",
                "D":"𝐃",
                "E":"𝐄",
                "F":"𝐅",
                "G":"𝐆",
                "H":"𝐇",
                "I":"𝐈",
                "J":"𝐉",
                "K":"𝐊",
                "L":"𝐋",
                "M":"𝐌",
                "N":"𝐍",
                "O":"𝐎",
                "P":"𝐏",
                "Q":"𝐐",
                "R":"𝐑",
                "S":"𝐒",
                "T":"𝐓",
                "U":"𝐔",
                "V":"𝐕",
                "W":"𝐖",
                "X":"𝐗",
                "Y":"𝐘",
                "Z":"𝐙",
                "a":"𝐚",
                "b":"𝐛",
                "c":"𝐜",
                "d":"𝐝",
                "e":"𝐞",
                "f":"𝐟",
                "g":"𝐠",
                "h":"𝐡",
                "i":"𝐢",
                "j":"𝐣",
                "k":"𝐤",
                "l":"𝐥",
                "m":"𝐦",
                "n":"𝐧",
                "o":"𝐨",
                "p":"𝐩",
                "q":"𝐪",
                "r":"𝐫",
                "s":"𝐬",
                "t":"𝐭",
                "u":"𝐮",
                "v":"𝐯",
                "w":"𝐰",
                "x":"𝐱",
                "y":"𝐲",
                "z":"𝐳",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        
        [
            "font_name":"𝐓𝐞𝐱𝐭 𝐅𝐚𝐧𝐜𝐲",
            "font":[
                "A":"𝐀",
                "B":"𝐁",
                "C":"𝐂",
                "D":"𝐃",
                "E":"𝐄",
                "F":"𝐅",
                "G":"𝐆",
                "H":"𝐇",
                "I":"𝐈",
                "J":"𝐉",
                "K":"𝐊",
                "L":"𝐋",
                "M":"𝐌",
                "N":"𝐍",
                "O":"𝐎",
                "P":"𝐏",
                "Q":"𝐐",
                "R":"𝐑",
                "S":"𝐒",
                "T":"𝐓",
                "U":"𝐔",
                "V":"𝐕",
                "W":"𝐖",
                "X":"𝐗",
                "Y":"𝐘",
                "Z":"𝐙",
                "a":"𝐚",
                "b":"𝐛",
                "c":"𝐜",
                "d":"𝐝",
                "e":"𝐞",
                "f":"𝐟",
                "g":"𝐠",
                "h":"𝐡",
                "i":"𝐢",
                "j":"𝐣",
                "k":"𝐤",
                "l":"𝐥",
                "m":"𝐦",
                "n":"𝐧",
                "o":"𝐨",
                "p":"𝐩",
                "q":"𝐪",
                "r":"𝐫",
                "s":"𝐬",
                "t":"𝐭",
                "u":"𝐮",
                "v":"𝐯",
                "w":"𝐰",
                "x":"𝐱",
                "y":"𝐲",
                "z":"𝐳",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        [
            "font_name":"𝓕𝓪𝓷𝓬𝔂",
            "font":[
                "A":"𝙰",
                "B":"𝙱",
                "C":"𝙲",
                "D":"𝙳",
                "E":"𝙴",
                "F":"𝙵",
                "G":"𝙶",
                "H":"𝙷",
                "I":"𝙸",
                "J":"𝙹",
                "K":"𝙺",
                "L":"𝙻",
                "M":"𝙼",
                "N":"𝙽",
                "O":"𝙾",
                "P":"𝙿",
                "Q":"𝚀",
                "R":"𝚁",
                "S":"𝚂",
                "T":"𝚃",
                "U":"𝚄",
                "V":"𝚅",
                "W":"𝚆",
                "X":"𝚇",
                "Y":"𝚈",
                "Z":"𝚉",
                "a":"𝚊",
                "b":"𝚋",
                "c":"𝚌",
                "d":"𝚍",
                "e":"𝚎",
                "f":"𝚏",
                "g":"𝚐",
                "h":"𝚑",
                "i":"𝚒",
                "j":"𝚓",
                "k":"𝚔",
                "l":"𝚕",
                "m":"𝚖",
                "n":"𝚗",
                "o":"𝚘",
                "p":"𝚙",
                "q":"𝚚",
                "r":"𝚛",
                "s":"𝚜",
                "t":"𝚝",
                "u":"𝚞",
                "v":"𝚟",
                "w":"𝚠",
                "x":"𝚡",
                "y":"𝚢",
                "z":"𝚣",
                "0":"𝟶",
                "1":"𝟷",
                "2":"𝟸",
                "3":"𝟹",
                "4":"𝟺",
                "5":"𝟻",
                "6":"𝟼",
                "7":"𝟽",
                "8":"𝟾",
                "9":"𝟿",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        
        [
            "font_name":"𓃥𓃠𓃰𓃱",
            "font":[
                "A":"𓃥",
                "B":"𓃠",
                "C":"𓃰",
                "D":"𓃱",
                "E":"𓃯",
                "F":"𓃭",
                "G":"𓃸",
                "H":"𓃵",
                "I":"𓃗",
                "J":"𓃘",
                "K":"𓃙",
                "L":"𓃟",
                "M":"𓄀",
                "N":"𓄁",
                "O":"𓄂",
                "P":"𓄃",
                "Q":"𓃚",
                "R":"𓃛",
                "S":"𓃜",
                "T":"𓃝",
                "U":"𓃞",
                "V":"𓃒",
                "W":"𓃓",
                "X":"𓃔",
                "Y":"𓃕",
                "Z":"𓃖",
                "a":"𓃡",
                "b":"𓃢",
                "c":"𓃦",
                "d":"𓃩",
                "e":"𓃫",
                "f":"𓃬",
                "g":"𓃮",
                "h":"𓃲",
                "i":"𓃴",
                "j":"𓃶",
                "k":"𓃷",
                "l":"𓃹",
                "m":"𓃻",
                "n":"𓃽",
                "o":"𓃾",
                "p":"𓃿",
                "q":"𓄄",
                "r":"𓄅",
                "s":"𓄆",
                "t":"𓄇",
                "u":"𓆇",
                "v":"𓆈",
                "w":"𓆉",
                "x":"𓆌",
                "y":"𓆏",
                "z":"𓆗",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        ,
        
        
        [
            "font_name":"ƬΣXƬ FΛПᑕY",
            "font":[
                "A":"𝙰",
                "B":"𝙱",
                "C":"𝙲",
                "D":"𝙳",
                "E":"𝙴",
                "F":"𝙵",
                "G":"𝙶",
                "H":"𝙷",
                "I":"𝙸",
                "J":"𝙹",
                "K":"𝙺",
                "L":"𝙻",
                "M":"𝙼",
                "N":"𝙽",
                "O":"𝙾",
                "P":"𝙿",
                "Q":"𝚀",
                "R":"𝚁",
                "S":"𝚂",
                "T":"𝚃",
                "U":"𝚄",
                "V":"𝚅",
                "W":"𝚆",
                "X":"𝚇",
                "Y":"𝚈",
                "Z":"𝚉",
                "a":"𝚊",
                "b":"𝚋",
                "c":"𝚌",
                "d":"𝚍",
                "e":"𝚎",
                "f":"𝚏",
                "g":"𝚐",
                "h":"𝚑",
                "i":"𝚒",
                "j":"𝚓",
                "k":"𝚔",
                "l":"𝚕",
                "m":"𝚖",
                "n":"𝚗",
                "o":"𝚘",
                "p":"𝚙",
                "q":"𝚚",
                "r":"𝚛",
                "s":"𝚜",
                "t":"𝚝",
                "u":"𝚞",
                "v":"𝚟",
                "w":"𝚠",
                "x":"𝚡",
                "y":"𝚢",
                "z":"𝚣",
                "0":"𝟶",
                "1":"𝟷",
                "2":"𝟸",
                "3":"𝟹",
                "4":"𝟺",
                "5":"𝟻",
                "6":"𝟼",
                "7":"𝟽",
                "8":"𝟾",
                "9":"𝟿",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        
        [
            "font_name":"🦒🦓🦌🦘",
            "font":[
                "A":"🦒",
                "B":"🦓",
                "C":"🦌",
                "D":"🦘",
                "E":"🦥",
                "F":"🦦",
                "G":"🦝",
                "H":"🐢",
                "I":"🐍",
                "J":"🦎",
                "K":"🐅",
                "L":"🐆",
                "M":"🐪",
                "N":"🐫",
                "O":"🦙",
                "P":"🐘",
                "Q":"🦏",
                "R":"🦛",
                "S":"🐐",
                "T":"🐏",
                "U":"🐑",
                "V":"🐎",
                "W":"🐃",
                "X":"🐂",
                "Y":"🐄",
                "Z":"🐖",
                "a":"🦇",
                "b":"🐒",
                "c":"🦍",
                "d":"🦧",
                "e":"🐝",
                "f":"🐛",
                "g":"🦋",
                "h":"🐌",
                "i":"🐞",
                "j":"🐜",
                "k":"🦗",
                "l":"🕷",
                "m":"🦂",
                "n":"🦟",
                "o":"🐮",
                "p":"🦁",
                "q":"🐯",
                "r":"🐨",
                "s":"🐼",
                "t":"🐻",
                "u":"🐰",
                "v":"🐹",
                "w":"🐭",
                "x":"🐱",
                "y":"🐶",
                "z":"🐷",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        
        [
            "font_name":"𝔗𝔢𝔵𝔱 𝔉𝔞𝔫𝔠𝔶",
            "font":[
                "A":"𝐀",
                "B":"𝐁",
                "C":"𝐂",
                "D":"𝐃",
                "E":"𝐄",
                "F":"𝐅",
                "G":"𝐆",
                "H":"𝐇",
                "I":"𝐈",
                "J":"𝐉",
                "K":"𝐊",
                "L":"𝐋",
                "M":"𝐌",
                "N":"𝐍",
                "O":"𝐎",
                "P":"𝐏",
                "Q":"𝐐",
                "R":"𝐑",
                "S":"𝐒",
                "T":"𝐓",
                "U":"𝐔",
                "V":"𝐕",
                "W":"𝐖",
                "X":"𝐗",
                "Y":"𝐘",
                "Z":"𝐙",
                "a":"𝐚",
                "b":"𝐛",
                "c":"𝐜",
                "d":"𝐝",
                "e":"𝐞",
                "f":"𝐟",
                "g":"𝐠",
                "h":"𝐡",
                "i":"𝐢",
                "j":"𝐣",
                "k":"𝐤",
                "l":"𝐥",
                "m":"𝐦",
                "n":"𝐧",
                "o":"𝐨",
                "p":"𝐩",
                "q":"𝐪",
                "r":"𝐫",
                "s":"𝐬",
                "t":"𝐭",
                "u":"𝐮",
                "v":"𝐯",
                "w":"𝐰",
                "x":"𝐱",
                "y":"𝐲",
                "z":"𝐳",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        
        [
            "font_name":"𓇟𓇣꧁꧂",
            "font":[
                "A":"✻",
                "B":"✼",
                "C":"✾",
                "D":"✿",
                "E":"❀",
                "F":"❁",
                "G":"❃",
                "H":"❇",
                "I":"❈",
                "J":"❉",
                "K":"❊",
                "L":"✢",
                "M":"✣",
                "N":"✤",
                "O":"✥",
                "P":"ꕥ",
                "Q":"𓇬",
                "R":"𓆸",
                "S":"𓆹",
                "T":"𓆼",
                "U":"𓇊",
                "V":"𓇚",
                "W":"𓇕",
                "X":"𓇗",
                "Y":"𓋇",
                "Z":"𓁙",
                "a":"𓁋",
                "b":"֍",
                "c":"𓆭",
                "d":"𓆰",
                "e":"𓆱",
                "f":"𓇋",
                "g":"𓇑",
                "h":"𓇛",
                "i":"ꕥ",
                "j":"𓇬",
                "k":"𓆸",
                "l":"𓆹",
                "m":"𓆼",
                "n":"𓇊",
                "o":"𓇚",
                "p":"𓇕",
                "q":"𓇗",
                "r":"𓋇",
                "s":"𓁙",
                "t":"𓆰",
                "u":"/",
                "v":"+",
                "w":"ꕥ",
                "x":"❀",
                "y":"꧂",
                "z":"꧁꧂",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        ,
        [
            "font_name":"𝙏𝙚𝙭𝙩 𝙁𝙖𝙣𝙘𝙮",
            "font":[
                "A":"𝐀",
                "B":"𝐁",
                "C":"𝐂",
                "D":"𝐃",
                "E":"𝐄",
                "F":"𝐅",
                "G":"𝐆",
                "H":"𝐇",
                "I":"𝐈",
                "J":"𝐉",
                "K":"𝐊",
                "L":"𝐋",
                "M":"𝐌",
                "N":"𝐍",
                "O":"𝐎",
                "P":"𝐏",
                "Q":"𝐐",
                "R":"𝐑",
                "S":"𝐒",
                "T":"𝐓",
                "U":"𝐔",
                "V":"𝐕",
                "W":"𝐖",
                "X":"𝐗",
                "Y":"𝐘",
                "Z":"𝐙",
                "a":"𝐚",
                "b":"𝐛",
                "c":"𝐜",
                "d":"𝐝",
                "e":"𝐞",
                "f":"𝐟",
                "g":"𝐠",
                "h":"𝐡",
                "i":"𝐢",
                "j":"𝐣",
                "k":"𝐤",
                "l":"𝐥",
                "m":"𝐦",
                "n":"𝐧",
                "o":"𝐨",
                "p":"𝐩",
                "q":"𝐪",
                "r":"𝐫",
                "s":"𝐬",
                "t":"𝐭",
                "u":"𝐮",
                "v":"𝐯",
                "w":"𝐰",
                "x":"𝐱",
                "y":"𝐲",
                "z":"𝐳",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        ,
        
        [
            "font_name":"𓀞𓀟𓀠𓀡",
            "font":[
                "A":"𓀞",
                "B":"𓀟",
                "C":"𓀠",
                "D":"𓀡",
                "E":"𓀢",
                "F":"𓀣",
                "G":"𓀤",
                "H":"𓀥",
                "I":"𓀦",
                "J":"𓀧",
                "K":"𓀨",
                "L":"𓀩",
                "M":"𓀪",
                "N":"𓀫",
                "O":"𓀬",
                "P":"𓀀",
                "Q":"𓁆",
                "R":"𓁇",
                "S":"𓁈",
                "T":"𓁉",
                "U":"𓁊",
                "V":"𓇚",
                "W":"𓇕",
                "X":"𓁋",
                "Y":"𓋇",
                "Z":"𓁙",
                "a":"𓁋",
                "b":"𓁌",
                "c":"𓆭",
                "d":"𓆰",
                "e":"𓆱",
                "f":"𓇋",
                "g":"𓇑",
                "h":"𓇛",
                "i":"𓁍",
                "j":"𓇬",
                "k":"𓆸",
                "l":"𓆹",
                "m":"𓆼",
                "n":"𓇊",
                "o":"𓇚",
                "p":"𓇕",
                "q":"𓁎",
                "r":"𓁑",
                "s":"𓁙",
                "t":"𓆰",
                "u":"/",
                "v":"+",
                "w":"ꕥ",
                "x":"❀",
                "y":"𓁐",
                "z":"𓁏",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ],
        
        [
            "font_name":"ÆÇÈÊ",
            "font":[
                "A":"𝐀",
                "B":"𝐁",
                "C":"𝐂",
                "D":"𝐃",
                "E":"𝐄",
                "F":"𝐅",
                "G":"𝐆",
                "H":"𝐇",
                "I":"𝐈",
                "J":"𝐉",
                "K":"𝐊",
                "L":"𝐋",
                "M":"𝐌",
                "N":"𝐍",
                "O":"𝐎",
                "P":"𝐏",
                "Q":"𝐐",
                "R":"𝐑",
                "S":"𝐒",
                "T":"𝐓",
                "U":"𝐔",
                "V":"𝐕",
                "W":"𝐖",
                "X":"𝐗",
                "Y":"𝐘",
                "Z":"𝐙",
                "a":"𝐚",
                "b":"𝐛",
                "c":"𝐜",
                "d":"𝐝",
                "e":"𝐞",
                "f":"𝐟",
                "g":"𝐠",
                "h":"𝐡",
                "i":"𝐢",
                "j":"𝐣",
                "k":"𝐤",
                "l":"𝐥",
                "m":"𝐦",
                "n":"𝐧",
                "o":"𝐨",
                "p":"𝐩",
                "q":"𝐪",
                "r":"𝐫",
                "s":"𝐬",
                "t":"𝐭",
                "u":"𝐮",
                "v":"𝐯",
                "w":"𝐰",
                "x":"𝐱",
                "y":"𝐲",
                "z":"𝐳",
                "0":"𝟎",
                "1":"𝟏",
                "2":"𝟐",
                "3":"𝟑",
                "4":"𝟒",
                "5":"𝟓",
                "6":"𝟔",
                "7":"𝟕",
                "8":"𝟖",
                "9":"𝟗",
                "-":"-",
                "/":"/",
                ":":":",
                ";":";",
                "(":"(",
                ")":")",
                ",":",",
                "$":"$",
                "&":"&",
                "@":"@",
                ".":".",
                "\"":"\"",
                "?":"?",
                "'":"'",
                "⌫":"⌫",
                "123":"123",
                "⬆️":"⬆️",
                "ABC":"ABC",
                "#+=":"#+=",
                "↩":"↩",
                "[":"[",
                "]":"]",
                "{":"{",
                "}":"}",
                "#":"#",
                "%":"%",
                "*":"*",
                "+":"+",
                "=":"=",
                "_":"_",
                "\\":"\\",
                "|":"|",
                "~":"~",
                "<":"<",
                ">":">",
                "€":"€",
                "£":"£",
                "¥":"¥",
                "^":"^",
                "!":"!",
                "🌐":"🌐",
                "·":"·"
            ]
        ]
        
        
    ]
}


